repository: jtaubenheim/markdown-template

output: web
# this property is useful for conditional filtering of content that is separate from the PDF.

topnav_title: markdown templates
# this appears on the top navigation bar next to the home button

site_title: markdown templates
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

company_name: JTaubenheim
# this appears in the footer

github_editme_path: https://github.com/jtaubenheim/markdown-template.git

host: 127.0.0.1
# the preview server used. Leave as is.

port: 4000
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.

exclude:
  - .idea/
  - .gitignore
  - vendor
  - bootstrap.min.css.map
# these are the files and directories that jekyll will exclude from the build

feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      search: true
      tooltip: true

# these are defaults used for the frontmatter for these file types

sidebars:
- markdown-sidebar

github: [metadata]


# Copyright 2021 Google LLC
